# Generated by Django 3.1.6 on 2021-06-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_disease', models.CharField(max_length=100)),
                ('symptom1', models.CharField(max_length=100)),
                ('symptom2', models.CharField(max_length=100)),
                ('symptom3', models.CharField(max_length=100)),
                ('symptom4', models.CharField(max_length=100)),
                ('symptom5', models.CharField(max_length=100)),
                ('symptom6', models.CharField(max_length=100)),
                ('symptom7', models.CharField(max_length=100)),
            ],
        ),
    ]
