# Generated by Django 3.1.6 on 2021-06-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locals', models.CharField(max_length=200)),
                ('good_for_treate', models.CharField(max_length=100)),
            ],
        ),
    ]
