# Generated by Django 3.1.6 on 2021-06-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_hospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='good_for_treate',
            new_name='specialist',
        ),
    ]
