# Generated by Django 3.1.6 on 2021-06-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210614_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='image',
            field=models.ImageField(default=0, upload_to='hospital'),
            preserve_default=False,
        ),
    ]
