# Generated by Django 3.1.6 on 2021-06-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='percentage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
