# Generated by Django 3.1.6 on 2021-06-18 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_disease_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='percentage',
        ),
    ]
