# Generated by Django 3.1.6 on 2021-06-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210619_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='symptom1',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptom2',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptom3',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptom4',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptom5',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptom6',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptom7',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
