# Generated by Django 3.1.6 on 2021-07-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210623_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=123)),
                ('email', models.EmailField(max_length=59)),
            ],
        ),
    ]
