# Generated by Django 3.1.6 on 2021-07-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='email',
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
